### ISSUE TITLE
Icons don't align properly

### ISSUE THREAD

**Issue by HDG-MrDeeJay** [rejax/TTT-EasyScoreboard#12]
Icons align dynamically to the text of the rank. This causes an issue when you have different lengthed ranks. Icons become misaligned and look ugly as a result.

-scorn

**Comment by rejax** [comment]
Have you tried editing `EZS.ShiftIconsWithLabels`?

**Comment by HDG-MrDeeJay** [comment]
yes, they still are out of alignment. I fixed it on my end by giving it 
its own column.
