### ISSUE TITLE
Invalid players can cause errors

### ISSUE THREAD

**Issue by HDG-MrDeeJay** [rejax/TTT-EasyScoreboard#13]
An error can occur in the console (that I don't have on me atm) clientside when a player leaves while the client is looking at the scoreboard. This error lasts for 1 or 2 frames.

-scorn

**Comment by Polarcraft** [comment]
@HDG-MrDeeJay This tends to happen a lot. It is when a player has the scoreboard open and one player leaves it causes this.

**Comment by HDG-MrDeeJay** [comment]
I know, and thus its a bug, because a simple IsValid check should fix that.

**Comment by rejax** [comment]
Are you running the latest version?
How can I reproduce this? (I haven't been able to)

**Comment by HDG-MrDeeJay** [comment]
Positive its the latest version.

Reproducable by holding tab and having someone leave

**Comment by Polarcraft** [comment]
I do not know if I fixed his issue, but I added IsValid at EZS_GetPlayerRankName hook.
