### ISSUE TITLE
Problems adding ranks

### ISSUE THREAD

**Issue by TSU-Nuked** [rejax/TTT-EasyScoreboard#17]
I am not the one putting the scoreboard in but there is a problem we need to have the ranks appear on the scoreboard could you please tell me how to to do that

**Comment by HDG-MrDeeJay** [comment]
Literally line 10.

https://github.com/rejax/TTT-EasyScoreboard/blob/master/lua/autorun/client/TTT_EasyScoreboard.lua#L10

**Comment by Linkfan123** [comment]
@HDG-MrDeeJay Good job on @rejax for adding those comments to simplify the process.
User-friendly-ness is a good thing to have in projects like this. :+1:
